import type { LucideIcon, LucideProps } from "lucide-react";
import {
  Archive,
  ArrowLeft,
  Bell,
  Bot,
  Brain,
  Briefcase,
  ChevronDown,
  ChevronUp,
  Check,
  CheckCircle2,
  ClipboardList,
  Clock,
  Copy,
  Cpu,
  Database,
  Download,
  Eye,
  ExternalLink,
  FileText,
  Folder,
  Hash,
  HelpCircle,
  Image,
  KeyRound,
  LayoutDashboard,
  Link,
  Lock,
  LockKeyhole,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minus,
  NotebookTabs,
  Paperclip,
  Pencil,
  Plus,
  RefreshCw,
  Reply,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Trash2,
  TrendingUp,
  User,
  UserPlus,
  Users,
  Wrench,
  X,
  Zap,
} from "lucide-react";

export const appIconMap = {
  admin: Shield,
  announcement: Megaphone,
  archive: Archive,
  arrowLeft: ArrowLeft,
  attachment: Paperclip,
  bot: Bot,
  briefcase: Briefcase,
  channel: Hash,
  check: Check,
  checkCircle: CheckCircle2,
  clock: Clock,
  close: X,
  copy: Copy,
  dashboard: LayoutDashboard,
  database: Database,
  download: Download,
  externalLink: ExternalLink,
  file: FileText,
  folder: Folder,
  help: HelpCircle,
  image: Image,
  key: KeyRound,
  link: Link,
  lock: Lock,
  secure: LockKeyhole,
  members: Users,
  memory: Brain,
  menu: Menu,
  message: MessageSquare,
  messageCircle: MessageCircle,
  minus: Minus,
  model: Cpu,
  note: NotebookTabs,
  notification: Bell,
  pencil: Pencil,
  plus: Plus,
  preview: Eye,
  refresh: RefreshCw,
  reply: Reply,
  search: Search,
  send: Send,
  settings: Settings,
  shieldCheck: ShieldCheck,
  task: ClipboardList,
  tools: Wrench,
  trash: Trash2,
  trending: TrendingUp,
  user: User,
  userPlus: UserPlus,
  users: Users,
  zap: Zap,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
} satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof appIconMap;

export interface AppIconProps extends LucideProps {
  fallback?: AppIconName;
  name: AppIconName;
}

export function AppIcon({ fallback = "file", name, ...props }: AppIconProps) {
  const Icon = appIconMap[name] ?? appIconMap[fallback];
  const ariaLabel = props["aria-label"];

  return <Icon aria-hidden={ariaLabel ? undefined : true} {...props} />;
}
