export const actionLabels = {
  accept: "Accept",
  add: "Add",
  approve: "Approve",
  cancel: "Cancel",
  back: "Back",
  check: "Check",
  choose: "Choose",
  clear: "Clear",
  close: "Close",
  connect: "Connect",
  continue: "Continue",
  copy: "Copy",
  create: "Create",
  decline: "Decline",
  delete: "Delete",
  disconnect: "Unlink",
  discard: "Discard",
  disable: "Turn off",
  dismiss: "Dismiss",
  done: "Done",
  edit: "Edit",
  enable: "Turn on",
  install: "Install",
  invite: "Invite",
  issue: "Issue",
  join: "Join",
  leave: "Leave",
  link: "Link",
  lookup: "Look up",
  more: "More",
  mention: "Mention",
  open: "Open",
  pin: "Pin",
  preview: "Preview",
  refresh: "Refresh",
  reject: "Reject",
  reload: "Reload",
  remove: "Remove",
  reset: "Reset",
  resolve: "Resolve",
  restart: "Restart",
  retry: "Retry",
  request: "Request",
  review: "Review",
  revoke: "Revoke",
  save: "Save",
  search: "Search",
  send: "Send",
  setup: "Set up",
  signIn: "Sign in",
  signOut: "Sign out",
  start: "Start",
  stop: "Stop",
  suspend: "Suspend",
  switch: "Switch",
  test: "Test",
  transcribe: "Convert",
  unlink: "Unlink",
  uninstall: "Remove",
  unblock: "Unblock",
  upload: "Upload",
  unpin: "Unpin",
  download: "Download",
  collapse: "Collapse",
  expand: "Expand",
  update: "Update",
  upgrade: "Upgrade",
  verify: "Verify",
  watch: "Watch",
} as const;

export type ActionKey = keyof typeof actionLabels;

export function actionLabel(action: ActionKey): string {
  return actionLabels[action];
}
